-- 01_setup.sql
-- Project: Toronto Airbnb Market Intelligence (Snowflake)
-- Layers: BRONZE (raw) -> SILVER (clean) -> GOLD (marts) + Cortex insights

-- Optional: set role if needed (only if you have permission)
-- USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE TORONTO_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE TORONTO_AIRBNB_INTEL;

CREATE OR REPLACE SCHEMA TORONTO_AIRBNB_INTEL.BRONZE;
CREATE OR REPLACE SCHEMA TORONTO_AIRBNB_INTEL.SILVER;
CREATE OR REPLACE SCHEMA TORONTO_AIRBNB_INTEL.GOLD;

USE WAREHOUSE TORONTO_WH;
USE DATABASE TORONTO_AIRBNB_INTEL;
USE SCHEMA TORONTO_AIRBNB_INTEL.BRONZE;

CREATE OR REPLACE FILE FORMAT TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE STAGE TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_STAGE
  FILE_FORMAT = TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_CSV_FF;
