-- 02_bronze_load.sql
-- Purpose: Load cleaned Toronto listings CSV into BRONZE layer

USE WAREHOUSE TORONTO_WH;
USE DATABASE TORONTO_AIRBNB_INTEL;
USE SCHEMA TORONTO_AIRBNB_INTEL.BRONZE;

-- 1) Create/replace raw table (Bronze = all STRING)
CREATE OR REPLACE TABLE TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW (
  ID STRING,
  NAME STRING,
  HOST_ID STRING,
  HOST_NAME STRING,
  NEIGHBOURHOOD_CLEANSED STRING,
  LATITUDE STRING,
  LONGITUDE STRING,
  ROOM_TYPE STRING,
  PRICE STRING,
  MINIMUM_NIGHTS STRING,
  AVAILABILITY_365 STRING,
  NUMBER_OF_REVIEWS STRING,
  LAST_REVIEW STRING,
  CALCULATED_HOST_LISTINGS_COUNT STRING
);

-- 2) (Recommended) Validate load first – returns parsing errors without loading
COPY INTO TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW
FROM @TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_STAGE/toronto_listings_clean.csv
FILE_FORMAT = (FORMAT_NAME = TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_CSV_FF)
VALIDATION_MODE = 'RETURN_ERRORS';

-- 3) Load data (after validation looks good)
COPY INTO TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW
FROM @TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_STAGE/toronto_listings_clean.csv
FILE_FORMAT = (FORMAT_NAME = TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_CSV_FF)
ON_ERROR = 'CONTINUE';

-- 4) Post-load checks (portfolio-friendly)
SELECT COUNT(*) AS bronze_rows_loaded
FROM TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW;

SELECT *
FROM TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW
LIMIT 10;
