-- 03_silver_transform.sql
-- Purpose: Clean + type-cast BRONZE listings into SILVER + create Data Quality view

USE WAREHOUSE TORONTO_WH;
USE DATABASE TORONTO_AIRBNB_INTEL;
USE SCHEMA TORONTO_AIRBNB_INTEL.SILVER;

-- 1) Create cleaned SILVER table (typed + deduped)
CREATE OR REPLACE TABLE TORONTO_AIRBNB_INTEL.SILVER.LISTINGS AS
SELECT
  TRY_TO_NUMBER(ID) AS ID,
  NULLIF(TRIM(NAME), '') AS NAME,
  TRY_TO_NUMBER(HOST_ID) AS HOST_ID,
  NULLIF(TRIM(HOST_NAME), '') AS HOST_NAME,
  NULLIF(TRIM(NEIGHBOURHOOD_CLEANSED), '') AS NEIGHBOURHOOD,

  TRY_TO_DECIMAL(LATITUDE, 9, 6) AS LATITUDE,
  TRY_TO_DECIMAL(LONGITUDE, 9, 6) AS LONGITUDE,

  NULLIF(TRIM(ROOM_TYPE), '') AS ROOM_TYPE,

  -- remove $ and commas safely
  TRY_TO_DECIMAL(REPLACE(REPLACE(TRIM(PRICE), '$', ''), ',', ''), 10, 2) AS PRICE,

  TRY_TO_NUMBER(MINIMUM_NIGHTS) AS MINIMUM_NIGHTS,
  TRY_TO_NUMBER(AVAILABILITY_365) AS AVAILABILITY_365,
  TRY_TO_NUMBER(NUMBER_OF_REVIEWS) AS NUMBER_OF_REVIEWS,
  TRY_TO_DATE(LAST_REVIEW) AS LAST_REVIEW,
  TRY_TO_NUMBER(CALCULATED_HOST_LISTINGS_COUNT) AS CALCULATED_HOST_LISTINGS_COUNT,

  CURRENT_TIMESTAMP() AS LOAD_TS
FROM TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW
WHERE TRY_TO_NUMBER(ID) IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRY_TO_NUMBER(ID) ORDER BY CURRENT_TIMESTAMP()) = 1;

-- 2) Data Quality view (SILVER)
CREATE OR REPLACE VIEW TORONTO_AIRBNB_INTEL.SILVER.V_LISTINGS_DATA_QUALITY AS
SELECT
  COUNT(*) AS total_rows,

  SUM(CASE WHEN PRICE IS NULL OR PRICE <= 0 THEN 1 ELSE 0 END) AS bad_price_rows,
  SUM(CASE WHEN LATITUDE IS NULL OR LONGITUDE IS NULL THEN 1 ELSE 0 END) AS missing_geo_rows,
  SUM(CASE WHEN NEIGHBOURHOOD IS NULL THEN 1 ELSE 0 END) AS missing_neighbourhood_rows,
  SUM(CASE WHEN ROOM_TYPE IS NULL THEN 1 ELSE 0 END) AS missing_room_type_rows,
  SUM(CASE WHEN MINIMUM_NIGHTS IS NULL THEN 1 ELSE 0 END) AS missing_minimum_nights_rows,
  SUM(CASE WHEN AVAILABILITY_365 IS NULL THEN 1 ELSE 0 END) AS missing_availability_rows,
  SUM(CASE WHEN NUMBER_OF_REVIEWS IS NULL THEN 1 ELSE 0 END) AS missing_reviews_rows,
  SUM(CASE WHEN LAST_REVIEW IS NULL THEN 1 ELSE 0 END) AS missing_last_review_rows,

  MIN(PRICE) AS min_price,
  MAX(PRICE) AS max_price,
  ROUND(AVG(PRICE), 2) AS avg_price
FROM TORONTO_AIRBNB_INTEL.SILVER.LISTINGS;

-- 3) Quick checks (portfolio-friendly)
SELECT COUNT(*) AS bronze_rows
FROM TORONTO_AIRBNB_INTEL.BRONZE.LISTINGS_RAW;

SELECT COUNT(*) AS silver_rows
FROM TORONTO_AIRBNB_INTEL.SILVER.LISTINGS;

SELECT *
FROM TORONTO_AIRBNB_INTEL.SILVER.V_LISTINGS_DATA_QUALITY;
